definitions:
  apperror.ReqError:
    properties:
      status:
        type: integer
      text:
        type: string
    type: object
  domain.SuccessRequest:
    properties:
      success:
        type: boolean
    type: object
  domain.Task:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  domain.TaskDTO:
    properties:
      description:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
host: localhost:5555
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: API для работа с задачами.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  version: "1.0"
paths:
  /tasks:
    get:
      consumes:
      - application/json
      description: Возвращает список задач с поддержкой пагинации и сортировки
      parameters:
      - description: Лимит
        in: query
        name: limit
        type: integer
      - description: Страница
        in: query
        name: page
        type: integer
      - description: Порядок сортировки (asc, desc)
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Task'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ReqError'
      summary: Получить список задач
      tags:
      - Tasks
    post:
      consumes:
      - application/json
      description: Добавить новую задачу с указанными данными
      parameters:
      - description: Данные задачи
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/domain.TaskDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ReqError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ReqError'
      summary: Добавить задачу
      tags:
      - Tasks
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет задачу по указанному ID
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/domain.SuccessRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ReqError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ReqError'
      summary: Удалить задачу
      tags:
      - Tasks
    get:
      consumes:
      - application/json
      description: Возвращает задачу по её ID
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ReqError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.ReqError'
      summary: Получить задачу по ID
      tags:
      - Tasks
    put:
      consumes:
      - application/json
      description: Обновляет данные существующей задачи
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      - description: Обновленные данные задачи
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/domain.TaskDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ReqError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ReqError'
      summary: Обновить задачу
      tags:
      - Tasks
swagger: "2.0"
